### ISSUE TITLE
GitHubAuthenticationOptions Setting Scope

### ISSUE THREAD

**Issue by BoasE** [RockstarLabs/OwinOAuthProviders#12]
Is there a reason why i can't set a scope ? Or is it a bug ? 

I'd like to set the scope because later on i want to use the auth token to trigger some github api functions .

Currenty i have to start a second authentication in order to activate the scopes

**Comment by jerriep** [comment]
The Scope is a list, so you just add to it:

```
GitHubAuthenticationOptions options = new GitHubAuthenticationOptions();
options.Scope.Add("scope to add");
app.UseGitHubAuthentication(options);
```
