### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by BoasE** [RockstarLabs/OwinOAuthProviders#14]
Hi
Are there any Plans for implementing stackoverflow oauth ?

**Comment by jerriep** [comment]
Hi @Gentlehag, this is not something I will likely have time for right now.  If someone else wants to pick this one up and submit a pull request it will be good.  The Stack Exchange API and authentication is available at http://api.stackexchange.com/docs/authentication

If I do have some time in the next few weeks, or just want a change of pace, I will look into it...

**Comment by ghost** [comment]
I used your project to learn about Owin Authentication Middleware. I have forked and implemented StackExchange. It seemed to work for me. You are welcome to use it if you like. Thanks.

**Comment by jerriep** [comment]
@payojbaral Please submit a pull request, thank you

**Comment by ghost** [comment]
I have initiated a pull request. This is my first such request. Please let me know if anything needs to be done differently or changed. Thank you again.

**Comment by jerriep** [comment]
Implemented in version 1.6.0
