### ISSUE TITLE
How to reuse Github Access Token

### ISSUE THREAD

**Issue by gcox** [RockstarLabs/OwinOAuthProviders#17]
This is probably a stupid question but once a user has authenticated via Github, I can't figure out how to access that user's access token again to make additional Github API calls.

**Comment by jerriep** [comment]
It is definitely not a stupid question :)

Here is an example of how you do it for Twitter: http://www.beabigrockstar.com/blog/get-the-twitter-profile-image-using-the-asp-net-identity/

The logic for doing it with Github is exactly the same.

**Comment by jennet** [comment]
FYI that link didn't work for me but I found it (I assume it's the same article) here http://www.jerriepelser.com/blog/get-the-twitter-profile-image-using-the-asp-net-identity
