### ISSUE TITLE
Signed assemblies in Nuget

### ISSUE THREAD

**Issue by DmitryPletenyov** [RockstarLabs/OwinOAuthProviders#18]
Hi

This package is used by a wide specter of different software solutions.
Including software with high security requirements. For this kind of solutions there is no way to use the unsigned assemblies, especially the third party assemblies.

It would be much easier for the package consumers to just import package without post-processing it.

Thanks in advance.

**Comment by leastprivilege** [comment]
you mean strong naming? When was that ever a security feature?

**Comment by jerriep** [comment]
@DmitryPletenyov from all I have read it sounds like strong naming creates more effort than it is worth, and there is a big effort from people to move away from it. If you absolutely need it, you are welcome to fork the project and build your own signed assemblies. 

The reference for my comments are the following:
[1] http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/
[2] https://github.com/octokit/octokit.net/issues/405
