### ISSUE TITLE
Use forWebApi

### ISSUE THREAD

**Issue by mey2021** [RockstarLabs/OwinOAuthProviders#21]
can i use this for webapi?

**Comment by jerriep** [comment]
If you can use the built in providers (i.e Facebook, Twitter, etc) for Web API, then you should be able to use these as well. Any reason you can't?

**Comment by mey2021** [comment]
quike response

thanks bro

any details for impliment?

**Comment by jerriep** [comment]
No sorry. You will need to search Google to find out how to secure a Web API using ASP.NET Identity. I assume you will have to build some OAuth infrastructure to allow people to authenticate against your API, and on the log in screen allow them to either log in using a username and password, or using one of the social login providers.

I do not have any specific details on how you will implement this however.
