### ISSUE TITLE
YahooAuthenticatedContext GetEmail(JObject user) is throwing errors

### ISSUE THREAD

**Issue by aaron-horst** [RockstarLabs/OwinOAuthProviders#24]
I am noticing exceptions in the YahooAuthenticatedContext GetEmail(JObject user) method with some user data returned via the Yahoo API.  The swallowed exception is "Cannot access child value on Newtonsoft.Json.Linq.JProperty." The shape of the JSON user looks like the following:

{
  "guid": "5J8UPK8SQ4UN37NCDQKCZ8AY7U",
  "ageCategory": "T",
  "created": "2014-08-06T19:04:10Z",
  "emails": {
    "handle": "someemailaddress@yahoo.com",
    "id": "1",
    "primary": "true",
    "type": "HOME"
  },
  "familyName": "doe",
  "gender": "M",
  "givenName": "john",
  "image": {
    "height": "192",
    "imageUrl": "https://s.yimg.com/dh/ap/social/profile/profile_b192.png",
    "size": "192x192",
    "width": "192"
  },
  "lang": "en-US",
  "memberSince": "2014-08-06T19:03:57Z",
  "nickname": "john",
  "phones": {
    "id": "1",
    "number": "1-55566666",
    "type": "MOBILE"
  },
  "profileUrl": "http://profile.yahoo.com/profileguidhere",
  "timeZone": "America/Los_Angeles",
  "isConnected": "true",
  "bdRestricted": "true"
}

**Comment by jerriep** [comment]
I am travelling at the moment with limited time available. Will look into this next week some time.

**Comment by jerriep** [comment]
@aaron-horst Is the JSON you pasted above 100% correct?  The emails element does not seem to be an array...?

**Comment by aaron-horst** [comment]
It was the exact json minus masking a few of the values returned back.  FWIW it was on a newly created Yahoo account and thanks for addressing this.

**Comment by jerriep** [comment]
Pleasure :D Hope all is sorted now

**Comment by ryanshelby** [comment]
Ah this could possibly be the reason why an email doesn't exist after calling AuthenticationManager.GetExternalLoginInfoAsync().  Could this be the reason why?  If so, will this fix be included in the next release?  Thanks so much.

**Comment by jerriep** [comment]
@ryanshelby Sometimes Yahoo simply just doesn't return the email address(es) and I have no explanation why.  On my own profile for example I have loaded multiple email addresses and the user profile information returned from Yahoo after login never included any of them.

So I am not sure that there is a defect on my side....
