### ISSUE TITLE
Get Private email frm Github Service

### ISSUE THREAD

**Issue by ygalbel** [RockstarLabs/OwinOAuthProviders#29]
Hi,
Do i have a possibility to access private email of  user after Github  authentification?
I think it should be in scope parameter in query to Github, but i can't change it.
Thanks for answer.

**Comment by jerriep** [comment]
@ygalbel you can set the scope as follows:

```
GitHubAuthenticationOptions options = new GitHubAuthenticationOptions
{
    ClientId = "",
    ClientSecret = ""
};
options.Scope.Add("user:email");
app.UseGitHubAuthentication(options);
```
