### ISSUE TITLE
LinkedIn authentication fails with 'invalid redirect_uri'

### ISSUE THREAD

**Issue by hanssens** [RockstarLabs/OwinOAuthProviders#30]
I've followed [the instructions](http://www.beabigrockstar.com/guides/aspnet-oauth/aspnet-mvc-linkedin-login) to the letter, but when not providing a redirect url for the LinkedIn OAuth provider the following error occurs:

![invalid_redirect_uri](https://cloud.githubusercontent.com/assets/493382/4304100/c1420ede-3e6d-11e4-82c3-3b4bfef4c5f1.png)

Luckily it can easily be resolved by adding your domain(s) to the **OAuth 2.0 Redirect URL's**. For example: `http://localhost:1123/signin-linkedin`

The [default CallbackPath ('signin-linkedin')](https://github.com/owin-middleware/OwinOAuthProviders/blob/431bf3c14b728e81fdedbdcbcf6930d73939eaa7/Owin.Security.Providers/LinkedIn/LinkedInAuthenticationOptions.cs#L93) is hardcoded and it seems to be neccessary to register it with LinkedIn now. So, the field cannot be left blank.

@jerriep: Perhaps a minor update to the _ASP.NET OAuth Guides_ will suffice to help others preventing this problem?

**Comment by jerriep** [comment]
Thank you for pointing this out @hanssens, I will update the guides. 

This must be something LinkedIn changed recently as it was not always required
