### ISSUE TITLE
Salesforce provider missing important claims 

### ISSUE THREAD

**Issue by sunres** [RockstarLabs/OwinOAuthProviders#33]
I was looking at the Salesforce provider and it seems to have passed minimal claims to the identity object. Some important ones are not there. I just wanted to confirm if you see adding any one of this as an issue

Access Token - Can be used to access any further information from Salesforce.

Refresh Token - Can be reused to regenerate access token without prompting again if access token expired. 

Organization_id - Very important parameter if you are using Multi-Tenant environment where connected app is granted access in customer environment where you need to know the org Id for future use.

Any insight on reason to ignore these would be highly appreciated. Also do you have plan to implement any caching of the tokens in provider (backed by database perhaps) for improving performance?

**Comment by jerriep** [comment]
First off please ensure to get latest version I just released from Nuget

Access token, refresh token and Organization ID can be retrieved from context after authentication. Configure the provider as follows:

```
var salesforceOptions = new SalesforceAuthenticationOptions
{
    Endpoints =
        new SalesforceAuthenticationOptions.SalesforceAuthenticationEndpoints
        {
            AuthorizationEndpoint =
                "https://ap1.salesforce.com/services/oauth2/authorize",
            TokenEndpoint = "https://ap1.salesforce.com/services/oauth2/token"
        },
    ClientId = "",
    ClientSecret = "",
    Provider = new SalesforceAuthenticationProvider()
    {
        OnAuthenticated = async context =>
        {
            System.Diagnostics.Debug.WriteLine(context.AccessToken);
            System.Diagnostics.Debug.WriteLine(context.RefreshToken);
            System.Diagnostics.Debug.WriteLine(context.OrganizationId);
        }
    }
};
app.UseSalesforceAuthentication(salesforceOptions);
```

To get a refresh token you must be sure to specify the correct scope for your application in Salesforce.

If you want to save the Access token, refresh token etc. in the database then please see this blog post I wrote on how to do it for Twitter:
http://beabigrockstar.com/blog/get-the-twitter-profile-image-using-the-asp-net-identity

The blog post demonstrates how to do it for Twitter, but the principle is the same for Salesforce or any other provider
