### ISSUE TITLE
Inquiry: Best way to obtain additional fields will full profile scope on LinkedIn

### ISSUE THREAD

**Issue by aaron-horst** [RockstarLabs/OwinOAuthProviders#34]
What would be the suggested approach for obtaining additional data back from the authentication response on LinkedIn when leveraging the bigger "r_fullprofile" scope?  I notice the AuthenticationHandler UserInfoEndpoint obviously doesn't have knowledge of the scopes and is set to only the core items.  What would be the best way to get additional properties added to the info endpoint (such as certifications, skills, etc.) so my code may consume them?

**Comment by jerriep** [comment]
Sorry for the long delay on this. Do you still need help with this?

**Comment by aaron-horst** [comment]
No, the pull request in changeset 3ad4f68 addresses how to accomplish this.

**Comment by jerriep** [comment]
Ok, that pull request is merged, so I am closing this issue.
