### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by patlac** [RockstarLabs/OwinOAuthProviders#5]
It would be nice if you could make github auth configurable: Currently, urls to github.com and api.github.com are hardcoded. As a matter of fact, there are also enterprises running github "on premise" [Github Enterprise](https://enterprise.github.com/).

the github.com then can possibly change to whetever host, and the api url changes to <yourcompanyhost>/api/v3

Would be nice if this was configurable, eg. read from setting. Of course forking and changing the hardcoded urls referring to github.com are an option (I just did), but configuration through settings would be nice, as anyone could still nuget the whole thing and just configure those settings.

**Comment by jerriep** [comment]
Hi @patlac, this has been added in the latest release which is published on NuGet.  The `GitHubAuthenticationOptions` class now contains an `EndPoints` property which allows you to specify custom OAuth endpoints, for example: 

``` csharp
app.UseGitHubAuthentication(new GitHubAuthenticationOptions
{
    ClientId = "",
    ClientSecret = "",
    Endpoints = new GitHubAuthenticationOptions.GitHubAuthenticationEndpoints
    {
        AuthorizationEndpoint = "<Endpoint>",
        TokenEndpoint = "<Endpoint>",
        UserInfoEndpoint = "<Endpoint>"
    }
});
```

Thank you for the suggestion!
